# Generated by Django 4.1 on 2022-10-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userrant_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrant',
            name='user_favorites',
        ),
    ]
