# Generated by Django 4.1.2 on 2022-10-24 22:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publication', '0004_alter_review_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='favorites',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
