# Generated by Django 4.1.1 on 2022-10-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0005_restaurant_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='likes',
            new_name='users_likes',
        ),
    ]
