# Generated by Django 4.1 on 2022-10-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_review_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='favorites',
            new_name='user_favorites',
        ),
    ]
