# Generated by Django 4.1 on 2022-10-26 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_rename_favorites_review_user_favorites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='user_favorites',
        ),
    ]
